"use client";
import { useEffect, useRef, useState } from "react";
import { calls, photos, voicemails } from "../data/phone-data";
import { getContactAvatar } from "../data/contact-avatars";
import { browserHistory } from "../data/browser-history";
import { BrowserArticle } from "./BrowserArticle";
import { ComputerTerminal } from "./ComputerTerminal";
import { ClockApp } from "./ClockApp";
import { PhoneHome } from "./PhoneHome";
import { MessagesApp } from "./MessagesApp";
import { MapApp } from "./MapApp";
import { introBeats } from "../data/intro-script";

const apps=[["/ui/icon_clock.svg","時間","custom mint"],["/ui/icon_chat.svg","簡訊","custom yellow"],["/ui/icon_photo.svg","相簿","custom pink"],["☎","通話紀錄","blue"],["齋","齋堂官網","red"],["G","Google","white"],["⌖","地圖","map-icon"]];
type PhoneView="home"|"clock"|"messages"|"calls"|"photos"|"website"|"google"|"map";
type GalleryMode="all"|"year"|"month"|"day";

export default function Home(){
 const[started,setStarted]=useState(false),[intro,setIntro]=useState(true),[line,setLine]=useState(0),[phone,setPhone]=useState(false),[computer,setComputer]=useState(false),[unlocked,setUnlocked]=useState(false),[code,setCode]=useState(""),[error,setError]=useState(false),[sceneFocus,setSceneFocus]=useState<"phone"|"light"|"screen"|null>(null),[lightOn,setLightOn]=useState(false);
 const[view,setView]=useState<PhoneView>("home"),[callTab,setCallTab]=useState<"records"|"voicemail">("records"),[photo,setPhoto]=useState<number|null>(null),[galleryMode,setGalleryMode]=useState<GalleryMode>("all"),[browserPage,setBrowserPage]=useState<number|null>(null);
  const photoSwipeStart=useRef<number|null>(null);
 const musicAudio=useRef<HTMLAudioElement|null>(null);
 const[musicOn,setMusicOn]=useState(false);
 useEffect(()=>{
  let audioContext:AudioContext|null=null;
  const playClick=(event:MouseEvent)=>{
   const target=event.target instanceof Element?event.target:null;
   if(!target?.closest("button, a, .cinematic-intro, [role='button']")||target.closest("audio, input, textarea"))return;
   audioContext??=new AudioContext();
   if(audioContext.state==="suspended")void audioContext.resume();
   const now=audioContext.currentTime,oscillator=audioContext.createOscillator(),gain=audioContext.createGain();
   oscillator.type="sine";
   oscillator.frequency.setValueAtTime(540,now);
   oscillator.frequency.exponentialRampToValueAtTime(820,now+.055);
   gain.gain.setValueAtTime(.0001,now);
   gain.gain.exponentialRampToValueAtTime(.065,now+.008);
   gain.gain.exponentialRampToValueAtTime(.0001,now+.075);
   oscillator.connect(gain);gain.connect(audioContext.destination);
   oscillator.start(now);oscillator.stop(now+.08);
  };
  document.addEventListener("click",playClick,true);
  return()=>{document.removeEventListener("click",playClick,true);if(audioContext)void audioContext.close()};
 },[]);
 useEffect(()=>{if(!started||!intro)return;const advanceKey=(event:KeyboardEvent)=>{if(event.code==="Space"||event.code==="Enter"){event.preventDefault();setLine(v=>{if(v>=introBeats.length-1){setIntro(false);return v}return v+1})}};window.addEventListener("keydown",advanceKey);return()=>window.removeEventListener("keydown",advanceKey)},[started,intro]);
 useEffect(()=>{if(!started)return;const screen=document.querySelector(".screen-hotspot");const openComputer=()=>setComputer(true);screen?.addEventListener("click",openComputer);return()=>screen?.removeEventListener("click",openComputer)},[started]);
 useEffect(()=>{const audio=new Audio("/MoonlitSilk.mp3");audio.loop=true;audio.volume=.38;musicAudio.current=audio;return()=>{audio.pause();musicAudio.current=null}},[]);
 useEffect(()=>{if(photo===null)return;const frame=requestAnimationFrame(()=>document.querySelector(".photo-filmstrip button.active")?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"}));return()=>cancelAnimationFrame(frame)},[photo]);
 const advance=()=>line<introBeats.length-1?setLine(line+1):setIntro(false); const press=(n:string)=>{setError(false);if(code.length<4)setCode(code+n)}; const unlock=()=>{if(code==="0828")setUnlocked(true);else{setError(true);setCode("")}};
 const openApp=(name:string)=>{if(name==="時間")setView("clock");else if(name==="簡訊")setView("messages");else if(name==="齋堂官網")setView("website");else if(name==="通話紀錄")setView("calls");else if(name==="相簿")setView("photos");else if(name==="Google")setView("google");else if(name==="地圖")setView("map")};
 const finishPhotoSwipe=(clientX:number)=>{if(photoSwipeStart.current===null)return;const distance=clientX-photoSwipeStart.current;photoSwipeStart.current=null;if(Math.abs(distance)<45)return;setPhoto(current=>current===null?current:distance<0?Math.min(photos.length,current+1):Math.max(1,current-1))};
 const startGame=()=>{setStarted(true);void musicAudio.current?.play().then(()=>setMusicOn(true)).catch(()=>setMusicOn(false))};
 const toggleMusic=()=>{const audio=musicAudio.current;if(!audio)return;if(musicOn){audio.pause();setMusicOn(false)}else void audio.play().then(()=>setMusicOn(true)).catch(()=>setMusicOn(false))};
 const sortedPhotos=[...photos].sort((a,b)=>new Date(b.modifiedAt).getTime()-new Date(a.modifiedAt).getTime()||b.id-a.id);
 const galleryGroups=sortedPhotos.reduce<{label:string;items:typeof sortedPhotos}[]>((groups,item)=>{
  const taken=new Date(item.modifiedAt),label=galleryMode==="year"?`${taken.getFullYear()} 年`:galleryMode==="month"?`${taken.getFullYear()} 年 ${taken.getMonth()+1} 月`:galleryMode==="day"?`${taken.getFullYear()} 年 ${taken.getMonth()+1} 月 ${taken.getDate()} 日`:"";
  const previous=groups.at(-1);if(previous?.label===label)previous.items.push(item);else groups.push({label,items:[item]});return groups;
 },[]);
 const PhoneHeader=({title}:{title:string})=><div className="phone-nav"><button onClick={()=>{setView("home");setPhoto(null)}}>‹</button><b>{title}</b><span/></div>;
 if(!started)return <main className="login-screen"><div className="login-effects" aria-hidden="true">{Array.from({length:14},(_,index)=><i className="login-sparkle" key={`sparkle-${index}`}/>)}{["🍓","🍬","🍓","🍬","🍓","🍬"].map((candy,index)=><span className="login-candy" key={`${candy}-${index}`}>{candy}</span>)}</div><div className="login-button-wrap"><button className="game-start-button" onClick={startGame}><i aria-hidden="true">🍓</i><b>遊戲開始</b><span>START</span></button></div></main>;
 return <main className="game-shell"><header><div className="brand"><span>齋</span>齋堂房屋不動產</div><button className={`music-toggle ${musicOn?"playing":""}`} onClick={toggleMusic} aria-label={musicOn?"關閉背景音樂":"開啟背景音樂"} aria-pressed={musicOn}><i>{musicOn?"♫":"♪"}</i><span>{musicOn?"音樂開啟":"音樂關閉"}</span></button></header>
 <section className="scene office-scene"><div className="office-stage" onMouseLeave={()=>setSceneFocus(null)}><picture><source media="(max-width:700px), (hover:none) and (pointer:coarse)" srcSet={lightOn?"/ui/bg_office_light_mobile.png":"/ui/bg_office_mobile.png"}/><img className="office-base" src={lightOn?"/ui/bg_office_light.webp":"/ui/bg_office.webp"} alt={lightOn?"亮著檯燈的午未辦公室":"午未老闆的辦公室"}/></picture><picture><source media="(max-width:700px), (hover:none) and (pointer:coarse)" srcSet="/ui/bg_office_phone_hover_mobile.webp"/><img className={`office-hover phone-highlight ${sceneFocus==="phone"?"visible":""}`} src="/ui/bg_office_phone_hover.webp" alt=""/></picture><picture><source media="(max-width:700px), (hover:none) and (pointer:coarse)" srcSet="/ui/bg_office_light_hover_mobile.webp"/><img className={`office-hover light-highlight ${sceneFocus==="light"?"visible":""}`} src="/ui/bg_office_light_hover.webp" alt=""/></picture><picture><source media="(max-width:700px), (hover:none) and (pointer:coarse)" srcSet="/ui/bg_office_screen_hover_mobile.webp"/><img className={`office-hover screen-highlight ${sceneFocus==="screen"?"visible":""}`} src="/ui/bg_office_screen_hover.webp" alt=""/></picture><button className="office-hotspot phone-hotspot" aria-label="查看桌上的手機" onMouseEnter={()=>setSceneFocus("phone")} onFocus={()=>setSceneFocus("phone")} onTouchStart={()=>setSceneFocus("phone")} onClick={()=>{setSceneFocus("phone");window.setTimeout(()=>setPhone(true),140)}}/><button className="office-hotspot light-hotspot" aria-label={lightOn?"關閉檯燈":"開啟檯燈"} aria-pressed={lightOn} onMouseEnter={()=>setSceneFocus("light")} onFocus={()=>setSceneFocus("light")} onTouchStart={()=>setSceneFocus("light")} onClick={()=>setLightOn(on=>!on)}/><button className="office-hotspot screen-hotspot" aria-label="查看電腦螢幕" onMouseEnter={()=>setSceneFocus("screen")} onFocus={()=>setSceneFocus("screen")} onTouchStart={()=>setSceneFocus("screen")} onClick={()=>setSceneFocus("screen")}/></div>
 {intro&&<div className={`intro cinematic-intro beat-${introBeats[line].kind}`} onClick={advance}><div className="film-grain"/><div className="cinema-bar top"/><div className="cinema-bar bottom"/><div className="cinema-title"><small>ZHAITANG PROPERTY</small><b>消失的天帝</b></div><div className="dialogue cinematic-card" key={line}><label>{introBeats[line].kind==="narration"?"旁白":introBeats[line].kind==="message"?"手機訊息":introBeats[line].kind==="sound"?"聲響":"辦公室內"}</label><button className="skip-intro" onClick={e=>{e.stopPropagation();setIntro(false)}}>略過對話</button><p>{introBeats[line].text}</p><div className="cinema-progress"><i style={{width:`${((line+1)/introBeats.length)*100}%`}}/></div><small className="beat-count">{String(line+1).padStart(2,"0")} / {introBeats.length}</small><button>{line===introBeats.length-1?"開始調查":"繼續"}　›</button></div><span className="advance-hint">點擊畫面或按空白鍵繼續</span></div>}</section>
 {computer&&<ComputerTerminal onClose={()=>setComputer(false)}/>} 
 {phone&&<div className="phone-overlay"><button className="round close" onClick={()=>setPhone(false)}>×</button><div className="device"><div className="notch"/>
 {!unlocked?<div className="lockscreen"><div className="status">10:24 <span>▮▮▮　●</span></div><div className="lock">⌁</div><h2>輸入密碼</h2><p>{error?"密碼錯誤，請再試一次":"4 位數密碼"}</p><div className="code">{[0,1,2,3].map(i=><i key={i} className={code.length>i?"filled":""}/>)}</div><div className="keypad">{["1","2","3","4","5","6","7","8","9","退格","0","確定"].map(k=><button key={k} onClick={()=>k==="退格"?setCode(code.slice(0,-1)):k==="確定"?unlock():press(k)}>{k}</button>)}</div><div className="hint">密碼是草莓糖小甜糕的生日</div></div>
 :<div className="phone-screen">
 {view==="home"&&<PhoneHome apps={apps} onOpen={openApp}/>} 
 {view==="clock"&&<ClockApp onBack={()=>setView("home")}/>} 
 {view==="messages"&&<MessagesApp onBack={()=>setView("home")}/>} 
 {view==="map"&&<MapApp onBack={()=>setView("home")}/>} 
 {view==="calls"&&<div className="phone-app calls-app"><PhoneHeader title="通話紀錄"/><div className="tabs"><button className={callTab==="records"?"active":""} onClick={()=>setCallTab("records")}>所有通話 <small>150</small></button><button className={callTab==="voicemail"?"active":""} onClick={()=>setCallTab("voicemail")}>未送出的語音 <small>{voicemails.length}</small></button></div>{callTab==="records"?<div className="call-list">{calls.map(c=>{const avatar=getContactAvatar(c.name,c.formal);return <div className="call-row" key={c.id}><div className="call-avatar-wrap">{avatar&&<img className="call-avatar" src={avatar} alt={`${c.name}的大頭貼`}/>}<i className={c.direction==="未接"?"missed":""}>{c.direction==="撥出"?"↗":c.direction==="來電"?"↙":"×"}</i></div><div><b>{c.name}</b><small className="contact-formal">正式名稱：{c.formal}</small><small>{c.direction}・{c.duration}</small></div><time>{c.day}<br/>{c.time}</time></div>})}</div>:<div className="voicemail-list">{voicemails.map(v=><div className="voicemail" key={v.id}><div><b>午未</b><small>{v.day} {v.time}・{v.duration}</small></div><audio controls preload="none" src={v.src}/><p>{v.text}</p></div>)}</div>}</div>}
 {view==="photos"&&<div className="phone-app gallery-app">{photo===null?<><PhoneHeader title="照片"/><div className="ios-album-head"><small>我的相簿</small><b>最近項目</b><span>{photos.length} 張照片</span></div><div className="ios-filter">{([['all','所有照片'],['year','年'],['month','月'],['day','日']] as const).map(([mode,label])=><button key={mode} className={galleryMode===mode?"active":""} onClick={()=>setGalleryMode(mode)}>{label}</button>)}</div><div className="gallery-scroll">{galleryGroups.map(group=><section className="photo-group" key={group.label||"all"}>{group.label&&<h3>{group.label}<small>{group.items.length} 張</small></h3>}<div className="gallery-grid">{group.items.map(p=><button key={p.id} onClick={()=>setPhoto(p.id)} aria-label={p.title}><img src={p.src} alt="" loading="lazy"/></button>)}</div></section>)}</div><nav className="ios-tabbar"><button>▧<small>圖庫</small></button><button>♡<small>為你推薦</small></button><button className="active">▣<small>相簿</small></button><button>⌕<small>搜尋</small></button></nav></>:<div className="photo-detail"><div className="ios-photo-nav"><button onClick={()=>setPhoto(null)}>‹ 最近項目</button><b>{photo} / {photos.length}</b><button aria-label="更多選項">•••</button></div><small className="photo-date">{photos[photo-1].date}</small><img className="big-photo" src={photos[photo-1].src} alt={photos[photo-1].title} draggable={false} onPointerDown={event=>{photoSwipeStart.current=event.clientX;event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={event=>finishPhotoSwipe(event.clientX)} onPointerCancel={()=>{photoSwipeStart.current=null}}/><div className="photo-caption"><b>{photos[photo-1].title}</b></div><div className="photo-filmstrip">{photos.map(p=><button className={p.id===photo?"active":""} key={p.id} onClick={()=>setPhoto(p.id)}><img src={p.src} alt="" loading="lazy" draggable={false}/></button>)}</div><nav className="photo-toolbar"><button onClick={()=>setPhoto(null)} aria-label="回到相簿首頁">▦</button><button disabled={photo===1} onClick={()=>setPhoto(photo-1)} aria-label="上一張">‹</button><button aria-label="喜歡">♡</button><button disabled={photo===photos.length} onClick={()=>setPhoto(photo+1)} aria-label="下一張">›</button></nav></div>}</div>}
 {view==="website"&&<div className="phone-app web-app"><PhoneHeader title="齋堂官網"/><div className="address">🔒 zhaitang.pages.dev</div><iframe title="齋堂房屋不動產官網" src="https://zhaitang.pages.dev/"/><a href="https://zhaitang.pages.dev/" target="_blank" rel="noreferrer">在完整瀏覽器開啟 ↗</a></div>}
 {view==="google"&&<div className="phone-app google-app">{browserPage===null?<><PhoneHeader title="Chrome"/><div className="google-logo"><i>G</i><span>oogle</span></div><a className="google-search" href="https://www.google.com/" target="_blank" rel="noreferrer">搜尋或輸入網址 <b>↗</b></a><div className="history-head"><b>瀏覽紀錄</b><span>午未的手機・10 筆</span></div><div className="browser-history">{browserHistory.map(h=><button key={h.id} onClick={()=>setBrowserPage(h.id)}><i>{h.category.slice(0,1)}</i><div><b>{h.title}</b><small>{h.site}・{h.time}</small><span>{h.query}</span></div><em>›</em></button>)}</div><nav className="browser-toolbar"><button>‹</button><button>›</button><button>＋</button><button>▢</button><button>•••</button></nav></>:<article className="fake-page"><div className="browser-address"><button onClick={()=>setBrowserPage(null)}>‹</button><span>🔒 {browserHistory[browserPage-1].site}.fake</span><button>⋮</button></div><div className="fake-site"><BrowserArticle record={browserHistory[browserPage-1]}/></div><nav className="browser-toolbar"><button onClick={()=>setBrowserPage(null)}>‹</button><button>›</button><button>＋</button><button>▢</button><button onClick={()=>setBrowserPage(null)}>⌂</button></nav></article>}</div>}
 <div className="homebar"/></div>}</div></div>}</main>
}
